import bpy
import bmesh
import os
import csv
import sys
from datetime import datetime

datefmt = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")

argv = sys.argv
argv = argv[argv.index("--") + 1:]

folder_path = argv[0]
output_csv = argv[1]

bpy.ops.wm.read_factory_settings(use_empty=True)

# --- Check if CSV exists ---
file_exists = os.path.isfile(output_csv)


def update_csv_row(filename, volume_cm3, area_cm2, hull_volume_cm3, hull_area_cm2, face_count, datefmt):
    nodule_name = filename.split("_")[0]


    csv_path = output_csv

    # Columns 0–6 are generated by code
    base_columns = [
        filename,
        nodule_name,
        f"{volume_cm3:.2f}",
        f"{area_cm2:.2f}",
        f"{hull_volume_cm3:.2f}",
        f"{hull_area_cm2:.2f}",
        face_count
    ]

    rows = []
    if os.path.exists(csv_path):
        with open(csv_path, newline='', encoding="utf-8") as f:
            rows = list(csv.reader(f))

    found = False
    for i, row in enumerate(rows):
        if len(row) > 1 and row[1] == nodule_name:
            found = True

            while len(row) < 13:
                row.append("")

            row[:7] = base_columns

            row[12] = datefmt
            break

    if not found:
        new_row = base_columns + [""] * 5 + [datefmt]
        rows.append(new_row)

    with open(csv_path, "w", newline='', encoding="utf-8") as f:
        csv.writer(f).writerows(rows)



with open(output_csv, 'a', newline='') as csvfile:
    writer = csv.writer(csvfile)

    # Write header only if file is new
    if not file_exists:
        writer.writerow([
            'Filename',
            'Nodule Name',
            'Volume (cm3)',
            'Surface Area (cm2)',
            'Convex Hull Volume (cm3)',
            'Convex Hull Surface Area (cm2)',
            'Faces',
            "Cruise",
            "Zone",
            "Station Box Core / Multi-Tube",
            "Collection Date",
            'Date'
        ])

    # --- Iterate OBJ files ---
    for filename in os.listdir(folder_path):
        if filename.lower().endswith('.obj'):
            filepath = os.path.join(folder_path, filename)

            # Import OBJ
            try:
                bpy.ops.wm.obj_import(filepath=filepath)
            except AttributeError:
                bpy.ops.import_scene.obj(filepath=filepath)

            # Assume the imported object is selected
            obj = bpy.context.selected_objects[0]

            if obj.type == 'MESH':
                # Apply transforms
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

                # Create BMesh
                mesh = obj.data
                bm = bmesh.new()
                bm.from_mesh(mesh)

                # --- Face count ---
                face_count = f"{len(bm.faces):,d}"
                
                # --- Calculate in meters ---
                area_m2 = sum(f.calc_area() for f in bm.faces)
                volume_m3 = bm.calc_volume(signed=False)

                # --- Convert to cm² / cm³ ---
                area_cm2 = round((area_m2 * 10000.0), 3)
                volume_cm3 = round((volume_m3 * 1000000.0), 3)

                # --- Replace mesh with convex hull ---
                bpy.context.view_layer.objects.active = obj
                bpy.ops.object.mode_set(mode='EDIT')
                bpy.ops.mesh.select_all(action='SELECT')
                bpy.ops.mesh.convex_hull(delete_unused=True)
                bpy.ops.object.mode_set(mode='OBJECT')

                # --- Recalculate BMesh for convex hull ---
                bm_convex = bmesh.new()
                bm_convex.from_mesh(obj.data)
                hull_area_m2 = sum(f.calc_area() for f in bm_convex.faces)
                hull_volume_m3 = bm_convex.calc_volume(signed=False)

                hull_area_cm2 = round(hull_area_m2 * 10000.0, 3)
                hull_volume_cm3 = round(hull_volume_m3 * 1000000.0, 3)

                print(f"{filename}:")

                print(f"  Volume: {volume_cm3} cm3")
                print(f"  Area: {area_cm2} cm3")
                print(f"  Convex Hull Volume: {hull_volume_cm3} cm3")
                print(f"  Convex Hull Area: {hull_area_cm2} cm2")
                print(f"  Faces: {face_count}")


                nodule_name = filename.split("_")[0]
                update_csv_row(
                    filename,
                    volume_cm3,
                    area_cm2,
                    hull_volume_cm3,
                    hull_area_cm2,
                    face_count,
                    datefmt
                )

                bm.free()

            # Delete object to clear scene for next import
            bpy.ops.object.delete()
    